server:
 port: 8888
spring:
 application:
  name: spring-cloud-config-service
 cloud:
  config:
   server:
    git:
     uri: https://github.com/aldeirfrancisco/config-service
     default-label: main
     search-paths:
     - 'greeting-service*'